# Generated by Django 3.0.3 on 2020-06-05 17:45

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='record',
            field=django_mysql.models.ListTextField(models.IntegerField(), default='', size=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='set_reps',
            field=models.CharField(blank=True, default='0*0', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise',
            field=models.ManyToManyField(blank=True, null=True, related_name='exc', through='tracker.WorkoutExercise', to='tracker.Exercise'),
        ),
    ]
