# Generated by Django 3.0.3 on 2020-06-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200605_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='set_reps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
