# Generated by Django 3.0.3 on 2020-06-11 19:03

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200611_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='record',
        ),
        migrations.AddField(
            model_name='exercise',
            name='set_record',
            field=django_mysql.models.ListTextField(models.CharField(max_length=50), default='', size=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight_record',
            field=django_mysql.models.ListTextField(models.CharField(max_length=50), default='', size=100),
        ),
    ]
